# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for macOS (.app bundle). Build with: scripts/build-macos.sh

import os

from PyInstaller.utils.hooks import collect_all

# Single source of truth for the version (see version.py).
_ns = {}
with open(os.path.join(SPECPATH, "version.py"), encoding="utf-8") as _f:  # SPECPATH is injected by PyInstaller
    exec(_f.read(), _ns)
VERSION = _ns["__version__"]

# Collect playwright Python package files
playwright_datas, playwright_binaries, playwright_hiddenimports = collect_all("playwright")

# Collect pywebview
webview_datas, webview_binaries, webview_hiddenimports = collect_all("webview")

# Collect playwright-stealth (ships a js/ folder with the evasion scripts)
stealth_datas, stealth_binaries, stealth_hiddenimports = collect_all("playwright_stealth")

# Native macOS notifications (UNUserNotificationCenter via PyObjC)
un_datas, un_binaries, un_hiddenimports = collect_all("UserNotifications")

a = Analysis(
    ["app.py"],
    pathex=["."],
    binaries=playwright_binaries + webview_binaries + stealth_binaries + un_binaries,
    datas=playwright_datas + webview_datas + stealth_datas + un_datas + [("assets", "assets")],
    hiddenimports=(
        playwright_hiddenimports
        + webview_hiddenimports
        + stealth_hiddenimports
        + un_hiddenimports
        + [
            "plyer",
            "plyer.platforms.macosx.notification",
            "flask",
            "sqlite3",
            "json",
        ]
    ),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Farejador",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # no terminal window
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Farejador",
)

app = BUNDLE(
    coll,
    name="Farejador.app",
    icon="assets/farejador.icns",  # generated by scripts/make-icons.py
    bundle_identifier="io.github.dgslv.farejador",
    info_plist={
        "CFBundleName": "Farejador",
        "CFBundleDisplayName": "Farejador de Aluguéis",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
    },
)
