"""Logo and icons — what the PyInstaller specs, the dashboard and the README reference.

The files are committed (generated by packaging/make-icons.py); if one goes missing
or gets corrupted, better to find out here than in the release build.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "packaging" / "icons"
STATIC = ROOT / "src" / "farejador" / "web" / "static"

PNG = b"\x89PNG\r\n\x1a\n"


def test_svg_source_exists():
    assert (ROOT / "assets" / "farejador.svg").read_text(encoding="utf-8").lstrip().startswith("<svg")


def test_readme_logo_and_dashboard_logo_are_the_same_png():
    readme_logo = (ROOT / "assets" / "logo.png").read_bytes()
    assert readme_logo[:8] == PNG
    assert (STATIC / "logo.png").read_bytes() == readme_logo


def test_windows_icon_is_an_ico():
    assert (ICONS / "farejador.ico").read_bytes()[:4] == b"\x00\x00\x01\x00"


def test_macos_icon_is_an_icns():
    assert (ICONS / "farejador.icns").read_bytes()[:4] == b"icns"


def test_specs_reference_the_icons_and_bundle_the_web_assets():
    mac = (ROOT / "packaging" / "farejador-macos.spec").read_text(encoding="utf-8")
    win = (ROOT / "packaging" / "farejador-windows.spec").read_text(encoding="utf-8")
    assert '"icons", "farejador.icns"' in mac
    assert '"icons", "farejador.ico"' in win
    for spec in (mac, win):
        assert '"farejador/web/templates"' in spec
        assert '"farejador/web/static"' in spec
        assert '"__main__.py"' in spec  # the single entry point
